devonfw-tutorials/tutorials

.github/workflows/checkpr.yml, .github/workflows/pr.yml
I added automatic checks for new PRs and added additional information to the automatically added comment on PRs.
=> Added checks and updated the help comment for PRs

.github/pull_request_template.md
I added a PR template to remind the contributor to think about the purpose of the tutorial. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> Initial PR template

autoReviewPullRequest.js
=> fix for request change message in auto review workflow

autoReviewPullRequest.js
=> use markdown language do display prerequisited and learning goals

devon4ng-mat-layout/index.asciidoc
=> Added Prerequisites, Learning goals and updated the Title

JumpTheQueue/index.asciidoc, cobigen/index.asciidoc, create-your-own-tutorial/index.asciidoc, devon4j-app/index.asciidoc, devonfw-ide/index.asciidoc
=> Updated titles and modified some text for betterment.

devon4j-architecture/index.asciidoc
=> fixing issues with devon4j architecture tutorial

.github/workflows/checkTutorialDescription.yml
=> renamed playbooks to tutorial-compiler

.github/workflows/buildPullRequest.yml
This is not a tutorial
This is not a tutorial
=> Make sure that there is only one build per tutorial

.github/workflows/syntaxCheckPullRequest.yml, package-lock.json, package.json, selectChangedFiles.js
=> Patch feature/syntaxChecking: selectChangedFiles script

devon4ng-architecture/files/layers-explained.md, devon4ng-architecture/index.asciidoc
=> Corrected spellchecks found in peer testing

.github/workflows/syntaxCheckPullRequest.yml
=> Patch feature/syntax checking

.github/workflows/syntaxCheckPullRequest.yml, getPlaybookCheckout.js
=> hotfix syntaxChecking

.github/workflows/syntaxCheckPullRequest.yml, getPlaybookCheckout.js
=> fixed bug syntax check

.github/workflows/syntaxCheckPullRequest.yml
=> added missing s

JumpTheQueue/index.asciidoc, autoReviewPullRequest.js, cobigen/index.asciidoc, devon4ng-mat-layout/index.asciidoc, devonfw-ide/index.asciidoc
=> new header structure

.github/workflows/buildMain.yml
=> dispatch to multiple repos

.github/workflows/buildMain.yml
Fixing the Bad Credentials error
=> changing the multiple repo dispatch variables

.github/workflows/buildMain.yml
=> changed from node@v2-beta to node@v2

JumpTheQueue/index.asciidoc, README.adoc, angular-mock-service/index.asciidoc, cobigen-setup/index.asciidoc, create-your-own-tutorial/index.asciidoc, devon4j-app/index.asciidoc, devon4j-architecture/index.asciidoc, devon4j-http-rest-client/index.asciidoc, devon4j-migrate/index.asciidoc, devon4ng-architecture/index.asciidoc, devon4ng-lazy-loading/index.asciidoc, devon4ng-mat-layout/index.asciidoc, devonfw-ide/index.asciidoc, openapi-generation-servicedocgen/index.asciidoc, openapi-generation-smallrye/index.asciidoc
Pull request for issue https://github.com/devonfw-tutorials/tutorials/issues/190
Added tags to all tutorials.
=> TUTORIALS-190 - Add tags to tutorials

JumpTheQueue/index.asciidoc, angular-mock-service/index.asciidoc, cobigen-setup/index.asciidoc, create-your-own-tutorial/index.asciidoc, devon4j-app/index.asciidoc, devon4j-architecture/index.asciidoc, devon4j-http-rest-client/index.asciidoc, devon4j-migrate/index.asciidoc, devon4ng-lazy-loading/index.asciidoc, devon4ng-mat-layout/index.asciidoc, devonfw-ide/index.asciidoc, openapi-generation-servicedocgen/index.asciidoc, openapi-generation-smallrye/index.asciidoc
=> refactoring tags

JumpTheQueue/index.asciidoc, devonfw-ide/index.asciidoc, openapi-generation-smallrye/index.asciidoc
=> syntax errors

README.adoc
exchanged the old Katacoda links to the new Killercoda links in the README.adoc file
=> Update Katacoda to Killercoda
